### ISSUE TITLE
Basic auth passwords containing `$` are not handled correctly

### ISSUE THREAD

**Issue by willgorman** [spinnaker/spin#171]
I've noticed that login fails with a `.spin/config` of

```
auth:
  enabled: true
  basic:
    username: someuser
    password: pas$word
```
 
After adding some more logging I can see that the value `spin` gets for the password is just `pas`.  If I escape the password like

```
auth:
  enabled: true
  basic:
    username: someuser
    password: pas$$word
```

then the value that `spin` attempts to use is `pasword`.  I've also tried double quotes, single quotes and multiline strings to see if there some way to get it to be preserved but haven't found anything that works yet.

**Comment by jtk54** [comment]
Spin interpolates the config file to try and resolve any env vars, so passwords with $ are likely being mangled by that processing.

**Comment by willgorman** [comment]
Thanks, that helps.  As a workaround I can set an environment variable `F00=\$` and then use this config

```
auth:
  enabled: true
  basic:
    username: someuser
    password: pas${FOO}word
```

**Comment by jtk54** [comment]
Does escaping in the config file not work properly?

**Comment by willgorman** [comment]
What's the right way to escape it?   I've tried  `$$` and `\$`

**Comment by jtk54** [comment]
I would expect that `\$` would work, but maybe there's some escaping in the golang yaml loading. Maybe try two: `\\$`?

**Comment by willgorman** [comment]
No luck with `\\$` either.  From the code for  `os.ExpandEnv` and also [this other issue](https://github.com/michaelsauter/crane/issues/51) it sounds like there's no escape character but spin could use os.Expand with a mapping instead to make it possible to do `$$`.

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed

**Comment by jmrodriguez-clv** [comment]
Same here. This is a YAML file, and a password field should contain any value (just using quotes for special cases should work):
```
auth:
  enabled: true
  basic:
    username: someuser
    password: '{pas$word'
```
It seems Spin is not escaping `$` correctly afterwards and it's getting expanded.

**Comment by jmrodriguez-clv** [comment]
> Spin interpolates the config file to try and resolve any env vars, so passwords with $ are likely being mangled by that processing.

And why is this done that way? This is a bad practice, IMHO.
I saw [the line doing this](https://github.com/spinnaker/spin/blob/3f5bbd0e6895a10f6b7be3a84a11085ed4cda74b/cmd/gateclient/client.go#L203), and the YAML file should be **unmarshaled first**, and escaped afterwards, or use a jinja2 or any other templating system that allows escape sequences easily.

**Comment by jmrodriguez-clv** [comment]
@willgorman a simple workaround is to define env vars:
```
export USERNAME=someuser
export PASSWORD='pas$word'
```

and define your yaml config with:
```
auth:
  enabled: true
  basic:
    username: '${USERNAME}'
    password: '${PASSWORD}'
```
so it will correctly interpolated, but if your $PASSWORD contains single quotes `'`, Spin will get confused :)
