### ISSUE TITLE
404 Apache/2.4.25 (Debian) Server at mydomain.com Port 9000

### ISSUE THREAD

**Issue by zot24** [spinnaker/spin#190]
Hi there!

I can't make it work and connect to my Spinnaker this is how my configuration looks like, however the tool keep saying that it's trying to connect to port 9000, I have trying to specify the port and use the flag too but it doesn't seems to be working.

My URL is https://mydomain.com there is no specific port just default one

I'm using 1.7.2 from where is getting that port value? 🤔 

```
gate:
  endpoint: https://mydomain.com
auth:
  enabled: true
  oauth2:
    authUrl: https://github.com/login/oauth/authorize
    tokenUrl: https://github.com/login/oauth/access_token
    clientId: CLIENT-ID
    clientSecret: CLIENT-SECRET
    scopes:
    - user:email
```

**UPDATE:** Forgot to attached the full error

```
Status: 404 Not Found, Body: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /applications was not found on this server.</p>
<hr>
<address>Apache/2.4.25 (Debian) Server at mydomain.com Port 9000</address>
</body></html>

```
